baseurl = "http://smashingthingstogether.com/"
languageCode = "en-us"
title = "Smashing Things Together"
publishDir = "docs"

[Params]
  author = "David Miranda"
  description = "Experiments, projects, and random ideas"

[permalinks]
  post = "/:slug/"